
Malicious Devices:  [3]
Client Labels:  {2: 590, 4: 580, 5: 558, 7: 1, 8: 2141}
Client Labels:  {2: 596, 4: 604, 5: 527, 8: 1, 9: 2456}
Client Labels:  {1: 6741, 2: 601, 3: 1, 4: 528, 5: 580, 7: 2436, 8: 1628}
Client Labels:  {2: 576, 4: 561, 5: 556, 6: 5917, 9: 1}
Client Labels:  {1: 1, 2: 594, 3: 3622, 4: 600, 5: 531}
Client Labels:  {2: 586, 4: 613, 5: 540, 6: 1, 7: 2167}
Client Labels:  {0: 5922, 2: 604, 4: 571, 5: 528}
Client Labels:  dict_keys([2, 4, 5, 7, 8, 9, 1, 3, 6, 0])
Client Indexes to use:  [0, 4, 1, 6, 2, 9, 5]
All Labels:  dict_keys([5, 0, 4, 1, 9, 2, 3, 6, 7, 8])
CR:   0%|                                                                                                         | 0/5 [00:00<?, ?it/s]/home/akshat/.local/lib/python3.9/site-packages/torchvision/transforms/functional.py:1603: UserWarning: The default value of the antialias parameter of all the resizing transforms (Resize(), RandomResizedCrop(), etc.) will change from None to True in v0.17, in order to be consistent across the PIL and Tensor backends. To suppress this warning, directly pass antialias=True (recommended, future default), antialias=None (current default, which means False for Tensors and True for PIL), or antialias=False (only works on Tensors - PIL will still use antialiasing). This also applies if you are using the inference transforms from the models weights: update the call to weights.transforms(antialias=True).
  warnings.warn(                                                                                                 | 0/10 [00:00<?, ?it/s]
 10%|██████████                                                                                          | 1/10 [00:07<01:10,  7.81s/it]
Device: 0 Epoch: 1/1 	Training Loss: 1.310439
Self Test Acc 55.00000000000001 %








Test Acc 10.0 %

Test Acc 34.0 %
Epoch: 1/1 	Training Loss: 1.310437
Self Test Acc 55.00000000000001 %
#########################Global Model Training###############
Epoch: 1/1 	Training Loss: 1.171214
Self Test Acc 71.0 %

  0%|                                                                                                             | 0/1 [00:00<?, ?it/s]
Epoch: 1/1 	Training Loss: 0.651587
Self Test Acc 96.0 %
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:09<00:00,  9.31s/it]
  0%|                                                                                                             | 0/1 [00:00<?, ?it/s]
Epoch: 1/1 	Training Loss: 0.846006
Self Test Acc 86.0 %
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.46s/it]
  0%|                                                                                                             | 0/1 [00:00<?, ?it/s]
Epoch: 1/1 	Training Loss: 1.005222
Self Test Acc 84.0 %
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.47s/it]
  0%|                                                                                                             | 0/1 [00:00<?, ?it/s]
Epoch: 1/1 	Training Loss: 1.183314
Self Test Acc 89.0 %
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.80s/it]
  0%|                                                                                                             | 0/1 [00:00<?, ?it/s]
Epoch: 1/1 	Training Loss: 0.584645

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:05<00:00,  5.04s/it]
CR:   0%|                                                                                                         | 0/5 [02:02<?, ?it/s]
Traceback (most recent call last):
  File "/home/akshat/project/train_loop.py", line 203, in <module>
    train_object.train()
  File "/home/akshat/project/train_loop.py", line 170, in train
    global_train_acc = utils.check_accuracy(DataLoader(dataset=train_dataset, batch_size = self.batch_size), self.global_network, self.device)
NameError: name 'train_dataset' is not defined